server:
  port: 8888
  servlet:
    context-path: /nishishabi
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.20.11:3306/wypt?useUnicode=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: JJ_passwd@2017

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/wy/server/auto/mapper/xml/*.xml
